# Generated by Django 4.1.2 on 2022-10-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
