# Generated by Django 4.1.2 on 2022-10-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categories_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
